pipeline:
  ckanta:
    image: python:3.6.6-alpine3.8
    commands:
      - apk add bash && pip install poetry
      - python -m venv /opt/ckanta
      - source /opt/ckanta/bin/activate
      - echo ${DRONE_REPO_LINK}
      - echo ${DRONE_REPO_LINK:7}
      - cd /drone/src/${DRONE_REPO_LINK:6}/hkmshb/ckanta
      - poetry develop
      - py.test
    when:
      branch: develop
