pipeline:
  ckanta:
    image: python:3.6.6-alpine3.8
    commands:
      - pip install poetry
      - python -m venv /opt/ckanta
      - sh /opt/ckanta/bin/activate
      - cd /drone/src/gitea.local.io/hkmshb/ckanta
      - python -c "import os; print(os)"
    when:
      branch: develop
