pipeline:
  ckanta:
    image: python:3.6.6-alpine3.8
    commands:
      - apk add bash && pip install poetry
      - python -m venv /opt/ckanta
      - source /opt/ckanta/bin/activate
      - echo ${DRONE_REPO}
      - cd /drone/src/${DRONE_REMOTE_URL}/hkmshb/ckanta
      - poetry develop
      - ls /opt/ckanta/bin
      - py.test
    when:
      branch: develop
