pipeline:
  ckanta:
    image: python:3.6.6-alpine3.8
    commands:
      - apk add bash && pip install poetry
      - python -m venv /opt/ckanta
      - source /opt/ckanta/bin/activate
      - cd /drone/src/gitea.local.io/hkmshb/ckanta
      - python -c "import os; print(os); print(os.getcwd());"
      - poetry develop
      - py.test
    when:
      branch: develop
