[tool.poetry]
name = "ckanta"
version = "0.1.0"
description = "Command-line tool for automating CKAN portal management tasks"
authors = ["Abdul-Hakeem Shaibu <hkmshb@gmail.com>"]

[tool.poetry.dependencies]
python = "3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.5"